name: Deploy to Azure Web App

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js 22.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      # Build Angular app
      - name: Build Angular App
        run: |
          cd client
          npm install
          npm run build

      # Prepare Express server and dependencies
      - name: Prepare Express Server
        run: |
          mkdir -p dist/server
          cp -r server/* dist/server/
          cp package.json dist/
          cp package-lock.json dist/
          cd dist
          npm install --production

      # Archive the build output
      - name: Archive Build Output
        run: |
          cd dist
          zip -r ../app.zip .
        working-directory: ./

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC81083B53824C71BEAFD768AE250A35 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9131DD006B2A4B7FB476D6CE8E35AD46 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9ED3790A2C344D4095059F14D716F696 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "random"
          package: "app.zip"
          slot-name: "Production"
